---
title: "storytelling"
author: "Fernando Almeida Barbalho"
date: '2024-11-19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(colorspace)
library(patchwork)

favelas_cor_trabalho <- readRDS("~/Github/favelas/favelas_cor_trabalho.rds")
municipios_cor_raca_perc_trabalho <- readRDS("~/Github/favelas/municipios_cor_raca_perc_trabalho.rds")

municipios_favela<- unique(favelas_cor_trabalho$cod_ibge)


mapa_estados<- geobr::read_state()
mapa_municipios_seat<- geobr::read_municipal_seat()



```


```{r fig.height=6, fig.width=10, fig.dpi= 300}

dados_favela_municipios<-
  municipios_cor_raca_perc_trabalho %>%
  filter(cod_ibge %in% municipios_favela) %>%
  mutate(agrupamento = "municipio") %>%
  bind_rows(
    favelas_cor_trabalho %>%
      mutate(agrupamento = "favela")
  )%>%
  filter(cor_raca %in% c("Branca", "Preta", "Parda"))  


favela_municipio_fake<- tibble(municipio = 1:100, favela= 1:100)



dados_favela_municipios %>%
  select(-municipio) %>%
  pivot_wider(names_from = agrupamento, values_from = percentual) %>%
  ggplot(aes(x=municipio, y=favela)) +
  geom_point( aes(fill = cor_raca), pch= 21, color = "black")+
  geom_point( aes(x = 76.34, y= 28.06), pch= 21, color = "black", fill = "#c87a8a", size =4 )+
  geom_point( aes(x = 76.19, y= 89.22), pch= 21, color = "black", fill = "#6b9d59", size =4 )+
  geom_smooth(data=favela_municipio_fake,method = "lm", color = "yellow", linetype = "dashed") +
  geom_text(aes(x = 90, y= 28.06 , label = str_wrap("Coronel Freitas-SC: 76% da população geral se identifica como branca, enquanto esse percentual chega a 28% entre os moradores de favelas",25)), color = "#c87a8a") +
  geom_text(aes(x = 40, y= 92 , label = str_wrap("Maués-AM: 76% da população geral se identifica como parda, enquanto esse percentual chega a 89% entre os moradores de favelas",80)), color = "#6b9d59") +
  scale_fill_discrete_qualitative(palette = "Dark 2") +
  theme_light() +
  theme(
    panel.grid =  element_blank() ,
    panel.background = element_rect(fill = "black"),
    plot.title = element_text(hjust = 0.5, size = 18, face = "bold"),
    plot.subtitle = element_text(hjust = 0.5, size = 14),
  
  ) +
  labs(
    title = "Desigualdades Raciais em Favelas e Municípios Brasileiros",
    subtitle = "Relação entre a composição racial da população geral e a dos moradores de favelas",
    x= "Proporção da população do município por cor/raça (%)",
    y= "Proporção da população em favelas por cor/raça (%)",
    fill = "cor/raça",
    caption = "Fonte: IBGE (censo 2022). Elaboração: Fernando Barbalho"
  )

ggsave( filename =  "grafico_dispersao.png")
```

```{r fig.height=14, fig.width=18, fig.dpi= 300}
mapa_favela_municipio_cor_seat_dif <-
  mapa_municipios_seat %>%
  inner_join(
    dados_favela_municipios %>%
      select(-municipio) %>%
      pivot_wider(names_from = agrupamento, values_from = percentual) %>%
      mutate(diferenca = municipio-favela) %>%
      mutate(code_muni= as.numeric(cod_ibge)) 
  )


mapa_favela_municipio_cor_seat_dif %>%
  #filter(cor_raca %in% c("Branca")) %>%
  ggplot() +
  geom_sf(data = mapa_estados, fill = NA) +
  geom_sf(aes( fill = diferenca, size = abs(diferenca)), pch = 21, alpha = 1, color = "black"  ) +
  scale_fill_continuous_divergingx(palette = "RdBu") +
  theme_void() +
  theme(
    panel.background = element_rect(fill = "black"),
    plot.title = element_text(hjust = 0.5, size = 18, face = "bold"),
    plot.subtitle = element_text(hjust = 0.5, size = 14),
    strip.background = element_rect(fill = "black"),
    strip.text = element_text(color = "white", size = 14, face = "bold" )
  ) +
  facet_wrap(cor_raca~.) +
  labs(
    title =  "Desigualdades Raciais em Favelas e Municípios Brasileiros",
    subtitle =  "Diferença entre proporção população município e proporção população favelas",
    fill = "Diferença",
    size = "Diferença",
    caption = "Fonte: IBGE (censo 2022). Elaboração: Fernando Barbalho"
  )


ggsave(filename = "mapa_2.jpg",height = 14, width = 18,  dpi = 300)

```


## Acréscimos


```{r}
dados_triangulos <- 
  left_join(
    favelas_cor_trabalho %>%
      select(cod_ibge, cor_raca, y = percentual),
    municipios_cor_raca_perc_trabalho %>%
      select(cod_ibge, cor_raca, x = percentual),
    by = c("cod_ibge", "cor_raca")
  ) %>%
  filter(cor_raca %in% c("Branca", "Preta", "Parda")) %>%
  mutate(
    uf = str_sub(cod_ibge, 1, 2),
    regiao = str_sub(uf, 1, 1)
  ) %>%
  arrange(cod_ibge, cor_raca)
```

```{r}
plota_triangulo1 <- function(regs = 1:5, rows = round(sum(c(7, 9, 5, 3, 4)[regs])^(1/3))) {
  dados_triangulos %>%
    filter(regiao %in% regs) %>%
    ggplot() +
    aes(x, y, group = cod_ibge) +
    coord_fixed() +
    geom_polygon(fill = NA, color = "white") +
    geom_point(aes(fill = cor_raca), pch = 21, size = if (rows <= 2) 1 else .8, color = "black") +
    facet_wrap(~ uf, nrow = rows) +
    scale_fill_discrete_qualitative(palette = "Dark 2") +
    theme_light() +
    xlim(0,100) + 
    ylim(0,100) + 
    theme(
      panel.grid =  element_blank() ,
      panel.background = element_rect(fill = "black"),
      plot.title = element_text(hjust = 0.5, size = 18, face = "bold"),
      plot.subtitle = element_text(hjust = 0.5, size = 14),
    ) +
    labs(
      title = "Desigualdades Raciais em Favelas e Municípios Brasileiros",
      subtitle = "Relação entre a composição racial da população geral e a dos moradores de favelas",
      x = "Proporção da população do município por cor/raça (%)",
      y = "Proporção da população em favelas por cor/raça (%)",
      fill = "cor/raça",
      caption = "Fonte: IBGE (censo 2022). Elaboração: Fernando Barbalho"
    )
}
```


```{r fig.height=6, fig.width=10, fig.dpi= 300}
plota_triangulo1()
# ggsave( filename =  "triangulo1_br.png")
plota_triangulo1(1)
# ggsave( filename =  "triangulo1_1.png")
plota_triangulo1(2)
# ggsave( filename =  "triangulo1_2.png")
plota_triangulo1(3, 1)
# ggsave( filename =  "triangulo1_3.png")
plota_triangulo1(4)
# ggsave( filename =  "triangulo1_4.png")
plota_triangulo1(5, 1)
# ggsave( filename =  "triangulo1_5.png")
```


```{r}
plota_triangulo2 <- function(regs = 1:5, rows = round(sum(c(7, 9, 5, 3, 4)[regs])^(1/3))) {
  dados_triangulos %>%
    filter(regiao %in% regs) %>%
    ggplot() +
    aes(x, y, group = cod_ibge) +
    coord_fixed() +
    geom_polygon(aes(color = cod_ibge), fill = NA, linewidth = .5) +
    geom_point(
      data = 
        dados_triangulos %>% 
        filter(
          regiao %in% regs, 
          cor_raca == "Parda"
        ),
      size = if (rows <= 2) 1 else .8, 
      color = "gray"
    ) +
    facet_wrap(~ uf, nrow = rows) +
    scale_color_discrete_qualitative(palette = "Dark 2", guide = "none") +
    theme_light() +
    xlim(0,100) + 
    ylim(0,100) + 
    theme(
      panel.grid =  element_blank() ,
      panel.background = element_rect(fill = "black"),
      plot.title = element_text(hjust = 0.5, size = 18, face = "bold"),
      plot.subtitle = element_text(hjust = 0.5, size = 14),
    ) +
    labs(
      title = "Desigualdades Raciais em Favelas e Municípios Brasileiros",
      subtitle = "Relação entre a composição racial da população geral e a dos moradores de favelas",
      x = "Proporção da população do município por cor/raça (%)",
      y = "Proporção da população em favelas por cor/raça (%)",
      fill = "cor/raça",
      caption = "Fonte: IBGE (censo 2022). Elaboração: Fernando Barbalho"
    )
}
```

```{r fig.height=6, fig.width=10, fig.dpi= 300}
plota_triangulo2()
# ggsave( filename =  "triangulo2_br.png")
plota_triangulo2(1)
# ggsave( filename =  "triangulo2_1.png")
plota_triangulo2(2)
# ggsave( filename =  "triangulo2_2.png")
plota_triangulo2(3, 1)
# ggsave( filename =  "triangulo2_3.png")
plota_triangulo2(4)
# ggsave( filename =  "triangulo2_4.png")
plota_triangulo2(5, 1)
# ggsave( filename =  "triangulo2_5.png")
```
